# AUTH SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: registry.digitalocean.com/art-registry/auth:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
---
# CATALOG SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: registry.digitalocean.com/art-registry/catalog:latest
        ports:
        - containerPort: 4000